#!/usr/bin/env bash
#Updates hostfile to change localhost and facebook.com to below:

cp /etc/hosts host_tmp
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts_tmp
cp -f ~/hosts.new /etc/hosts
